# 项目地址：https://github.com/xxjwxc/gormt
# 安装方式：go install github.com/xxjwxc/gormt@master
# 在 config.yml 同目录下执行 gormt 即可生成代码

base:
  is_dev: false
out_dir: ./model/gen  # 输出目录
url_tag: json # web url tag(json,db(https://github.com/google/go-querystring))
language: 中 文  # 语言(English,中 文)
db_tag: gorm # 数据库标签(gorm,db)
simple: false # 简单输出(默认gorm标签不输出)
is_out_sql: false # 是否输出 sql 原信息
is_out_func: true # 是否输出 快捷函数
is_foreign_key: false # 是否导出外键关联
is_gui: false  # 是否ui模式显示
is_table_name: false # 是否直接生成表名,列名
is_null_to_point: false # 数据库默认 'DEFAULT NULL' 时设置结构为指针类型
is_web_tag: false
is_web_tag_pk_hidden: false
table_prefix: "" #表前缀
db_info:
  host: devenv.d8s.fun
  port: 3306
  username: my_flomo
  password: my_flomo
  database: my_flomo
  type: 0 # 数据库类型:0:mysql , 1:sqlite , 2:mssql
